services:
  Auto_Finance_MCP:
    build: .  # 使用当前目录的 Dockerfile
    container_name: Auto_Finance_MCP_Server
    ports:
      - "8000:8000"  # 映射主机 8000 → 容器 8000
    #environment:
    #  - GAODE_API_KEY=${GAODE_API_KEY}  # 从环境变量注入密钥
    restart: unless-stopped  # 异常时自动重启
    volumes:
      - ./logs:/app/logs  # 挂载日志目录（可选）
    networks:
      - auto_finance_net

networks:
  auto_finance_net:  # 自定义网络（便于后续扩展其他服务）
    driver: bridge